### ISSUE TITLE
What f0 estimation algorithm was used?

### ISSUE THREAD

**Issue by seungwonpark** [auspicious3000/icassp_2020_demo#2]
Hi, Kaizhi

I hope all is well regarding the covid-19 situation.
I recently read your f0-conditioned AutoVC paper, but I could not found a reference for f0 estimation algorithm. Can you point me a reference for that?

Thanks in advance.

**Comment by auspicious3000** [comment]
We use rapt.

**Comment by seungwonpark** [comment]
Thank you very much.
